### ISSUE TITLE
FR: Setting for ‘XP Award’ listed on Tracker to not take Party Size into account to better match RAW

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#10166]
Since it’s just cosmetic and you can usually do simple math while hovering the current number to do this I get why you might not want to add a setting like this, but I figured since it has rules support it’d be worth asking. Thanks either way; I really appreciate all your guys have done.

https://2e.aonprd.com/Rules.aspx?ID=574

Page 507 of CRB “ When the group overcomes an encounter with creatures or hazards, each character gains XP equal to the total XP of the creatures and hazards in the encounter **(this excludes XP adjustments for different party sizes; see Party Size on page 508 for details)**”

Under Party Size on Page 508 of CRB: “The rules for advancement assume a group of four PCs. The rules for encounters (page 489) describe how to accommodate groups of a different size, **but the XP awards don’t change—always award the amount of XP listed for a group of four characters.**”

**Comment by TMunsie** [comment]
The math being done changes the XP budget per these guidelines. Effectively we normalize the adjustment from page 498 to number of players. Are you asking that we simply sum all the XP and divide by 4 instead of normalizing to the tier per the rules?

Right now, the system will, say for an encounter budget of moderate (80 XP) for four players will convert the excess XP for 6 players (80 XP plus 20 plus 20 for a total of 120 XP) back to 80, which is the intent of the rules you’re quoting - awarding all players 80 XP per the direction of “award the XP as if there are 4 players” directive. What is your specific ask for the recomputation? What value should the XP be, because the rules you reference lead to this scenario.

**Comment by GorgoPrimus** [comment]
Ah, I see what you mean. And I now realize that you can pretty much always get the number I’m asking for by looking at the first anyways. Sorry for the confusion.
