### ISSUE TITLE
FR: add the ability for reoccuring saves from spells via rules elements.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#10642]
I had this issue with the spell crushing despair: https://2e.aonprd.com/Spells.aspx?ID=57

which potentially can ask the player to make a save on their turn for 1 minute or 10 rounds. currently there isnt a quick way to reference the dc via an inline send from the spell. what i have to do to reference to the correct dc is to fake cast the spell to get the inline send dc from the spell to go to the chat. 

i propose an idea for the fix to have an effect that causes a reoccuring spell save via the rules elements that could be open to at the beginning or end of a pcs turn depending on the spell requirements.  that if the requirements were met it would send to chat the dc of the spell that the effect came from at the beginning of their turn each time for them to save. without having to do the above.

**Comment by galaara98** [comment]
would like to see this also....  
i think we all have had things where the chat is too far away.  Perhaps things that have rounds, or sustain, etc. could use some sort of generic "effect" (so they can be terminated early, etc.), and the effect can be codified to be able to put an action or free action as is appropriate (actions for things like sustain this effect, or free action for things marked as it just keeps happening), so that players can just click the "temporarily" available action to regurgitate the chat message.

**Comment by Incantatio** [comment]
I would also like these effects to be tracked in some way, not only for players but also for NPCs as well.  

For these spells maybe see if their effect can make use of some of the existing reminder functionality like Stunned / Slowed / Quickened reminding you how many actions you have at the start of your turn or the Ongoing Damage reminder / recovery check at the end of turn.  

Even if it doesn't include the DC the reminder that a check needs to be rolled and for what spell / effect would be an improvement (but if we can somehow get the DC in there even better).

**Comment by simonward** [comment]
You can always right-click the chat card and choose "Pop Out Message".

**Comment by TikaelSol** [comment]
Consolidating into #4882
