### ISSUE TITLE
New Remaster Cauldron feat needs daily crafting coding

### ISSUE THREAD

**Issue by theJLUnit** [foundryvtt/pf2e#11595]
The new Cauldron feat has no daily crafting for its temporary items. I have some code from the Witches+ version but it's not working on this feat:

{"isDailyPrep":true,"key":"CraftingEntry","selector":"cauldron","craftableItems":[{"or":[{"and":["item:trait:potion"]},{"and":["item:trait:oil"]}]}]}

{"key":"ActiveEffectLike","mode":"upgrade","path":"system.crafting.entries.cauldron.maxItemLevel","value":"@actor.level","phase":"beforeDerived"}

**Comment by ottyn** [comment]
I did something similar by copying some of the REs from the Alchemist Dedication and Infused Reagents feats and modifying them.

![image](https://github.com/foundryvtt/pf2e/assets/97130150/1bcb7c70-1e8b-40d6-b234-682c3a7078b6)

This allowed my witch character to have a crafting area for the Cauldron feat and complete daily crafting, but unfortunately, it doesn't do any limitations on the crafting.  She can click the button multiple times and create potions.  This will definitely need to be fixed in code.
![image](https://github.com/foundryvtt/pf2e/assets/97130150/7b51d2aa-f7ad-4262-94f7-ce8d43d7867c)
