### ISSUE TITLE
Cone templates automatically snap to corner and can't be placed orthogonally anymore

### ISSUE THREAD

**Issue by Smendrik** [foundryvtt/pf2e#11942]
When I use the "place cone template" option from the chat after using a spell the template will always snap automatically to one of the nearest corners, and ignores orthogonally placement.

**Comment by Suldrun45** [comment]
This also seems to affect line and emanation templates - the snap to corner effect should only affect bursts according to https://2e.aonprd.com/Rules.aspx?ID=354 and to the areas diagram https://2e.aonprd.com/Images/Rules/Rules354.png (although for the orthogonal templates it is not clear since the diagram shows differences between the 15 feet and larger templates)

**Comment by Smendrik** [comment]
I played around a bit and found out you can get the orthognal template while hovering over a corner with the template and use Ctrl+scroll
