### ISSUE TITLE
Thaumaturge - Implement Paragon RE broken

### ISSUE THREAD

**Issue by AporieTM** [foundryvtt/pf2e#12909]
When leveling up as a Thaumaturge to level 17 there is no pop-up to select the implement to become paragon.

Instead I get a yellow error message saying "test has no valid options for Implement Paragon."

**Comment by simonward** [comment]
Have you tried setting the character to level 0, and then back to 17?

**Comment by TikaelSol** [comment]
This may be due to an earlier error on the actor, either because a dialog was closed or the actor was imported and a flag was never set. Setting them to level 0 then back up and reselecting your implements should fix it. If this was an imported actor report the error to the importer module's author.
![image](https://github.com/foundryvtt/pf2e/assets/80183198/350509ca-84c4-43e0-b64f-542ff0fc5b88)
