### ISSUE TITLE
Kineticist ABP not functioning properly.

### ISSUE THREAD

**Issue by MrPatchy** [foundryvtt/pf2e#14761]
Playing a Kineticist, with ABP, I didn't gain the +1 you would normally get from gate attenuator, and even adding a gate attenuator to the sheet and investing it didn't add the bonus to my Elemental blasts. There isn't a proficiency to manually add it, so as far as I can tell, the only option is to add the +1 manually every time I attack. 

The game is balanced around these bonuses so it's kinda rough we've been missing out on it (we keep forgetting we aren't gaining the bonus). We have 2 kineticists in the party, both are having the same problem.

**Comment by stwlam** [comment]
We aren't in a position to make the game for fun when running certain builds in spite of Paizo's mistakes (or maybe intentional decisions: they haven't commented on this particular topic and very likely won't ever). You are probably not alone in being discontented here, however, so you might have some luck joining the foundry system's discord server for advice.

Off the top of my head, changing the bonus type on the attenuator to something other than "item" would give you the bonus.

**Comment by TMunsie** [comment]
> Playing a Kineticist, with ABP, I didn't gain the +1 you would normally get from gate attenuator, and even adding a gate attenuator to the sheet and investing it didn't add the bonus to my Elemental blasts. There isn't a proficiency to manually add it, so as far as I can tell, the only option is to add the +1 manually every time I attack.
> 
> The game is balanced around these bonuses so it's kinda rough we've been missing out on it (we keep forgetting we aren't gaining the bonus). We have 2 kineticists in the party, both are having the same problem.

I'll direct your attention to the following: 
**Automatic Bonus Progression** - GM core, page 83: This variant removes the **item bonus** to rolls and DCs...
**Gate Attenuator** - Rage of Elements, page 224: If you're a kineticist, the attenuator grants you a +1 **item bonus** to your impulse attack modifier...

We have literally implemented the Rules as Written. I would suggest commenting on the Paizo Forums or not running with ABP. Members of the community have made things like Automatic Rune Progression which is probably closer to what most people want. Because the only thing I can tell you, right now, is that under ABP you are adding a modifier that you should not be adding per the rules. Whether or not you want to do that, the system imposes the limit because of RAW. But as shark mentioned we have lots of ways for you to ignore the rules if your GM wants. Asking us to change RAW is not appropriate. Convince Paizo and we'll implement it as errata as quickly as possible.
