### ISSUE TITLE
Feature Request: Change the code in the elemental blast portion of the different kinetic gates to allow for any trait to be added to the blast.

### ISSUE THREAD

**Issue by Silversongs** [foundryvtt/pf2e#15140]
I am creating my own Kineticist element for a homebrew campaign and ran into an issue. The code inside the (Element) gate that creates the elemental blast can be totally customized except for the line that reads element: "air" or whatever element you have. You can only input the base elements which makes it impossible to get the correct trait on the blast. This might be quick to fix (I only know the basics of coding), and is, as far as I'm aware, the only unsolvable issue with creating a new elemental gate.

**Comment by Silversongs** [comment]
Ignore the close reopen, I tapped the wrong thing.

**Comment by MrVauxs** [comment]
Can you provide an example of what you mean? If your issue was in regards to creating a new Elemental Blast option, https://github.com/foundryvtt/pf2e/pull/15099 has recently been merged that allows for EffectTraits (and thus, **feat traits**, which can be configured by modules or in the homebrew traits settings menu) to be used for blasts.

**Comment by Silversongs** [comment]
Reading what you linked, that should certainly fix my issue. Void is actually the trait I'm using funnily enough.
