### ISSUE TITLE
Dragonslayer Shield

### ISSUE THREAD

**Issue by RodiakWolfshain** [foundryvtt/pf2e#15170]
Could you please update the table for Resistances, since the normal colorcoding isnt valid anymore. Thank you :)

Maybe something like

<tbody>
<tr>
<td>Fortune</td>
<td>Force</td>
</tr>
<tr>
<td>Horned, Conspirator</td>
<td>Poisen</td>
</tr>
<tr>
<td>Mirage. Omen</td>
<td>Mental</td>
</tr>
<tr>
<td>Diabolic</td>
<td>Fire</td>
</tr>
<tr>
<td>Empyreal</td>
<td>Spirit</td>
</tr>
<tr>
<td>Adamantine</td>
<td>Bludgeoning</td>
</tr>
</tbody>

**Comment by TikaelSol** [comment]
Since the table isn't on the item itself we'll be removing it from the description entirely (it was never part of the description, in fact).

Tables like this are better done in journals, which we could link to from relevant items. This is something we'll definitely keep in mind as we look to revise the system's rules journals to something more usable.
