### ISSUE TITLE
Player Core 2 Herbalist Archetype Feat Fresh Ingredients not able to be used

### ISSUE THREAD

**Issue by Icarus-the-phoenix** [foundryvtt/pf2e#15686]
The Fresh Ingredient Feat is categorized as a skill feat instead of an archetype feat and it sends an error message when trying to add it to a class or archetype feat slot. 

The error is: 
"foundry.js:72040 Cannot add feat "Fresh Ingredients" to Archetype Feats: feat type is invalid."

![image](https://github.com/user-attachments/assets/45066fec-4fe6-4e16-a7f4-900c8df9b940)

**Comment by TMunsie** [comment]
It is a skill feat that belongs to an archetype. It cannot be slotted into a free archetype slot because RAW those only take class feats, not skill feats. Please see the CounterFAQ for an explanation. If you wish to override this, add it to bonus feats, remove the skill trait, and then it will be able to be slotted.

**Comment by Icarus-the-phoenix** [comment]
Oh, I see. Sorry, I misunderstood archetype skill feats.
