### ISSUE TITLE
Having a buckler on one arm does not count as a free hand for purpose of the "Fist" weapon

### ISSUE THREAD

**Issue by MoritzGr** [foundryvtt/pf2e#15788]
![image](https://github.com/user-attachments/assets/2f8f61ff-f76a-4301-8b46-ed751a9881d4)

If my character is holding a buckler and another weapon (Here a 1+ Hands weapon, but 1 hand behaves the same) in one hand each, the "Fist" weapon (in this example gained from Deific Weapon: Irori) will fail to recognize the hand assigned to the Buckler as free.

![image](https://github.com/user-attachments/assets/bb7e79e8-52a3-4937-84e4-50b6795e217c)

**Comment by stwlam** [comment]
This works as intended.

**Comment by CarlosFdez** [comment]
More specifically, though it is a bit strange, fists are explicitly supposed to be treated as free hand weapons, and free hand weapons cannot be used if anything is being wielded in that hand.

**Comment by MoritzGr** [comment]
Fair enough.

Though technically a buckler is never stated to be in your hand, just strapped to you forearm. It's just the foundry system that implemented it as "Held 1H" to be able to implement it the same as other shields.

**Comment by CarlosFdez** [comment]
Its actually not buckler, its cause of fist. A fist is to be treated as a free hand weapon, and the free hand trait has certain restrictions.

Basically, fist doesn't require a free hand. Instead, it requires you to not be wielding anything in that hand. This may sound like the same thing, but those two states are not mutually exclusive and result in consequences.

**Comment by Payden-Pringle** [comment]
@CarlosFdez, "having a Buckler strapped to your arm while not gripping it" is not wielding it. You are only wielding it if you grip it, such as to get the Shield Bash attack with it.

Neither state is relevant when having a Buckler on one arm and anything else in your other hand.
Fist attacks can be used with that configuration due to this.

https://2e.aonprd.com/Rules.aspx?ID=2149
> You’re wielding an item any time you’re holding it in the number of hands needed to use it effectively.

i.e. if you aren't gripping the Buckler, it is not being wielded.
This does not stop you from Raising it, due to the text in the item's description.

@stwlam, I think this issue should be re-opened, because even if that's intended, it prevents play in Foundry from matching what's actually possible mechanically in the PF2e system.

**Comment by CarlosFdez** [comment]
While this specific interaction isn't in the FAQ, the fist free weapon thing is mentioned there:

> An unarmed attack can't be Disarmed. It also doesn't take up a hand, though a fist or other grasping appendage generally works _**like a free-hand weapon**_. - PC 283

**Comment by CarlosFdez** [comment]
As for the rest of your point, bucklers do count as wielded, because shields in geneeral do:
>  Your character must be wielding a shield in one hand to make use of it, and it grants its bonus to AC only if they use an action to Raise a Shield.

I say this as someone who believed you could punch with bucklers, and was pointed to specific evidence. Unfortunately, shark is right. This is a natural consequence of Paizo writing out rules as fail states instead of allowed states.

**Comment by Payden-Pringle** [comment]
Interesting. Thanks for that information.

I do not see where the hand is wielding the Buckler in that case, however.
From your earlier comment:
> and free hand weapons cannot be used if anything is being wielded in that hand.

If a Buckler is not gripped, but is being wielded, it's not being wielded by the hand of the arm it is strapped to.
It's being wielded with 0 hands. Because you're not gripping it, and the exception text in its description lets you do that.

The entire crux of this conversation is whether the hand should be unavailable for other things when the Buckler isn't Gripped.
And my understanding of what you're saying is that having a Buckler strapped to an arm is wielding it even if the hand isn't Gripping it, so the hand is treated as occupied.

But that statement is only saying "it's being wielded". Not "it is being wielded by specifically that hand."

The reason this distinction is important is because it's what's making the Free-Hand reference you bring up relevant.
> You can’t attack with a free-hand weapon if you’re wielding anything in that hand or otherwise using that hand.

If that reference isn't relevant, then the Fist attack isn't affected by a Buckler in any case.

If it's this text from the Shield rules that's causing the hand to be treated as occupied:
> Your character must be wielding a shield in one hand to make use of it, and it grants its bonus to AC only if they use an action to Raise a Shield.

The Buckler text is the exception to this statement, so it doesn't apply in this case.
Because you can make use of a Buckler without it being in your hand due to its exception text.
The only two reasonable outcomes from the exception text in the Buckler item are:
1. You can Raise the Buckler in the conditions the text describes, and your hand remains free when doing so.
2. You can Raise the Buckler in the conditions the text describes, and your hand becomes occupied by doing so.

But the idea that the actual outcome of the text is:
3. You can Raise the Buckler in the conditions the text describes, but your hand was _always_ occupied by having it on.

Appears to be unsupported based on the above.

It also creates this weird distinction where a Buckler is more restricting in this way, because you have to take it off to avoid that occupied status for your hand.

Whereas, you can just release a Steel Shield and utilize the now free hand, then grip the Steel Shield later, because you're not wielding the Steel Shield while you do that since you can't use it like that given it lacks the exception text.

My point in expressing this is to say: The interpretation that a Buckler always occupies the hand creates a situation that I would expect to be untrue for how bad it is. The opposite of "too good to be true": That seems "too bad to be true".

All this to ask: **What rule causes `wielding` to take up the hand in the Buckler's case, given its exception text?**
Because, if there's not any, it doesn't. And if it doesn't, it doesn't interfere with a Fists attack because **free-hand** becomes unrelated.

**Comment by Payden-Pringle** [comment]
That's unfortunate.

> The hand with a buckler is both _free_ and _wielding something_.

What makes _specifically the hand_ wield the Buckler? You can wield something with 0 hands if that's what it requires to use.
If it's the Shield rules text, the Buckler's exception text directly addresses that.

Without writing another large comment, it's untenable to treat a hand as both free & wielding something at the same time.
Which takes precedent when I need to open a door with it? The Wielding or the Free?

More importantly, what rules text clarifies whatever the answer is?
My only point in asking that question is to point out how this is untenable.

**Comment by CarlosFdez** [comment]
Neither, interact says you use your hands, so if your hand is available you're go. Its not based on precedence, its based on requirements. Its actually quite tenable.

Its very clear you're going to a major length to try to force a specific interpretation through the system. Trying to do so on a RAW argument unfortunately isn't going to work, the RAW is clear, even if I think its strange.
