### ISSUE TITLE
Psychic: Fire shield doesnt get morphed into cold for oscilating wave subclass.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#15822]
https://2e.aonprd.com/ConsciousMinds.aspx?ID=3

the issue is that fire shield doesnt change to protection from fire or immunity to fire damage damage when the remove energy is selected. 
it also needs to do cold damage as a button.

https://2e.aonprd.com/Spells.aspx?ID=1529&Redirected=1

**Comment by ThingsCouldGetDicey** [comment]
> https://2e.aonprd.com/ConsciousMinds.aspx?ID=3
> 
> the issue is that fire shield doesnt change to protection from fire or immunity to fire damage damage when the remove energy is selected. 
it also needs to do cold damage as a button.

https://2e.aonprd.com/Spells.aspx?ID=1529&Redirected=1

**Comment by ammalagonc** [comment]
Hey there, 

So the Cold Damage is already part of the default behavior when using the Oscillating Wave Toggle. If you choose `remove energy`, the spell will render it as Cold damage instead of fire.

![image](https://github.com/user-attachments/assets/fbe2c69d-61e0-44d4-99c1-7cafc4a68e5b)

The other piece will be added once this PR gets approved.

Thanks.
