### ISSUE TITLE
Remaster changes (identical items from old CRB)

### ISSUE THREAD

**Issue by tpegasus79** [foundryvtt/pf2e#15896]
Just in case you guys are still taking information to add to the remaster changes list for item name changes from CRB. Here is a list of items to help others with switches of items from premaster to remaster. 

Necklace of Fireballs has changed to the Frozen lave (consumable version) and Eternal Eruption (permanent) items in the GM Core.

Hate of the Magi is now Mage's Hat

Boots of Elvenkind is now Arboreal Boots. There is a slight change to the wording but mechanically they are the same so the item. The wording is changed I think to not just be tried to one ancestry

Cloak of Elvenkind is now Cloak of Illusions

Rod of Wonder became Madcap Top

Arrow-catching Shield is Lodestone Shield

Spell-storing Rune is now Spell Reservoir Rune

Dancing Rune is Animated Rune

Salve of Slipperiness became Tricky Liniment

I know you guys have more important items but just thought I would send some finds.  You guys do amazing work and thank you for all you do.

**Comment by ammalagonc** [comment]
Hi There, 

Thanks again for submitting this info. So that you know, the system still has the following items available:

Boots of Elvenkind, Cloak of Elvenkind, Necklace of Fireballs, Rod of Wonder, and Arrow-catching Shield.

Everything else will be added to the Wiki and the Remaster journal (upon the next release, assuming the change gets approved beforehand).

Thanks again :)
