### ISSUE TITLE
CTRL+Drag to Measure and Drop Waypoints not functional when Drag Measurement is Active

### ISSUE THREAD

**Issue by aburley1234** [foundryvtt/pf2e#15961]
FoundryVTT v12.330
PF2E Version 6.2.1
Drag Measurement Setting - Always

Ctrl-Dragging while having the "Select Tokens" tool selected no longer starts a measurement.
Ctrl-Dragging from a token while having the "Select Tokens" tool selected does not put you into the state where you can drop waypoints

**Comment by Khunkurisu** [comment]
I don't mean to be rude, but is feature request really the right label for this if the request is "don't disable a feature that has no reason to be disabled"? And if there's something about the implementation that requires it, that feels more like a bug or flaw in the implementation of the new ruler.

**Comment by cuyima** [comment]
It's not actually just the Select Tokens tool. It's the Measure Distance one as well, making it impossible to use waypoints with any of the tools :/

**Comment by Khunkurisu** [comment]
To be clear measurements while dragging tokens works fine. This is not related to that.

If you use the Foundry built in measurement alongside any popular tool module (Token Drag Ruler, Elevation Ruler, etc), you can access the measurement tool from the default select tool by holding the Control key and dragging the cursor.

This core functionality is disabled by the PF2e system’s ruler implementation, instead ctrl dragging has the same functionality as dragging with the select tool does with no modifiers. (Leading me to believe that the issue is likely just the implementation ignoring modifiers entirely and not passing the function to core.)

At any rate to ensure the folks working on the system have the cleanest experience possible PLEASE make separate issues for things that aren’t related to this one.

**Comment by tyrielv** [comment]
It looks to me like the problem is [here](https://github.com/foundryvtt/pf2e/blob/515c1a062fc92b78887a2f0ff7f9026864ee0c8b/src/module/canvas/ruler.ts#L8C5-L10C6):
```
static override get canMeasure(): boolean {
        return this.#dragMeasurement ? game.activeTool === "ruler" : super.canMeasure;
    }
```
If the PF2E system's drag measurement is enabled (either set to "Always," or set to "In Combat" and it's in combat), then canMeasure will only return true if the active tool is the ruler. Super.canMeasure will also return true if Ctrl+Drag is used.

**Comment by RisingStarPF2e** [comment]
This really needs to be fixed. This can't be intentional. This basically means you need to pick between using these timeless controls but have no deep module support because all of them utilize the base measure now OR use the modules but now you need to click on the ruler, double check your back on that token layer.

Especially on a bigger setup, it's just a nightmare of fighting years of muscle memory and sighing every time I use a special macro or a module that requires a certain layer to work properly. ETC.
