### ISSUE TITLE
Wrong wording for: PF2E.SpecificRule.Equipment.ChimeraFlail.StrideHalfLabel

### ISSUE THREAD

**Issue by RodiakWolfshain** [foundryvtt/pf2e#16005]
Stride is not "at least half speed"- it should be "max half speed"

**Comment by simonward** [comment]
Source? My PDF contains “If your last action was to Stride at least half your Speed, this does an additional 1d4 force damage.”

**Comment by ammalagonc** [comment]
Hello, 

As @simonward mentioned in their reply, the Howl of the Wild PDF does not utilize the wording "max half speed" on the ability. 

I also checked Demiplane and AoN to see if there was a discrepancy but they are an exact match with what is in the source document (HotW PDF). 

Can you please advise what the intent of the change is?

**Comment by RodiakWolfshain** [comment]
Ok... If this is correct, then the Chimera Flail - Lion discription is incorrect.
"Effect You tap into the predator speed of a lion. You Stride up to half your Speed and make a Strike against a target. If that creature is within reach of an ally, regardless if they would normally provide flanking or not, that creature is considered off-guard to your Strike. Your additional precision damage against an off-guard creature increases to 1d4. After using this, the lion head loses its additional precision damage. You can spend 10 minutes to rest and recharge the head."

**Comment by ammalagonc** [comment]
I believe I understand what's going on - there are two references to "You Stride up to half your Speed". One of them is for the Goat and the other is for Lion. The " Stride up to half your Speed" toggle appears on the Goat head but not the Lion.

The toggle appears when "Goat" is selected because it will add a 1d4 to the damage roll -
`Goat If your last action was to Stride at least half your Speed, this does an additional 1d4 force damage.`

For Pouncing Whirl, you don't require a toggle. The Goat `Stride at least half your Speed` means you can move/stride up to half your total speed as part of the action.

Does that make sense?

**Comment by RodiakWolfshain** [comment]
Ahhhh.... Ok... Yes. Thank you. That make sense. Ok... Case closed. Sorry guys :)

**Comment by ammalagonc** [comment]
All good!

Happy gaming :)
