### ISSUE TITLE
Overlays Forge Barrage

### ISSUE THREAD

**Issue by bernardoclon** [foundryvtt/pf2e#16088]
Good day, The Force Barrage spell should offer different variations depending on the number of actions invested.

**Comment by ammalagonc** [comment]
Hello, 

Thank you for the suggestion. This was already brought up by another member of the community (https://github.com/foundryvtt/pf2e/issues/15309). 

Because of the unique way Force Barrage works, implementing variants would not do much in terms of improving functionality/automation. 

PF2e Workbench currently provides a Macro that allows for this functionality.
