### ISSUE TITLE
Conditions are affecting the Critical Specialization DC of Bows

### ISSUE THREAD

**Issue by MothMariner** [foundryvtt/pf2e#16368]
The DC 10 for removing the missile pinning effect of the bow critical specialization is being affected by conditions on the attacking creature, and it should not be.

Recreation: 
Give a universal negative condition (sickened, frightened) to a creature with bow critical specialization.
Do a crit.
See the DC has dropped.

pf2e 6.3.1
foundry 12.331

**Comment by TikaelSol** [comment]
Not sure this isn't how it should work. This is something Paizo would need to clarify. As is the DC originates from the attacking creature and all other DCs originating from them are reduced, so RAW the system is correct.

If Paizo indicates otherwise or we find something in the rules stating that some DCs should be static (like flat checks have) then we can change the behavior.
