### ISSUE TITLE
[Suggestion] Enable an option to make nonlethal strikes besides the regular ones.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1948]
In GitLab by @sandersontavares on Dec 28, 2021, 23:10

**Comment by KSops** [comment]
Is this ticket specifically for taking the -2 circumstance penalty and adding the `nonlethal` trait? Or is this scope also to automate nonlethal attacks making the target unconscious rather than marked as defeated?

What about weapons that are already nonlethal like unarmed strike? Should this "new button" simply the toggled opposite depending on whether the weapon has lethal/nonlethal? Feels like maybe this should be a roll option to toggle "lethality".

**Comment by stwlam** [comment]
Closing in favor in #7018 , which is a more-complete request
