### ISSUE TITLE
Feature Request: Action Category Icons

### ISSUE THREAD

**Issue by bland-html** [foundryvtt/pf2e#2400]
Since nothing is really happening with Action Categories, I was thinking it would be useful to have small icons next to the Heading of Actions based on their Action Category. 

So if it was an Offensive Action, you could put a sword.
Defensive = Shield. Interaction = Hands. 

That way, if an NPC has 3 Actions, but one of them is a combat only, it'll be easier to see at a glance vs remembering.

**Comment by TMunsie** [comment]
The issue with this is that these terms exist solely for organizational purposes on the character sheet. They only say where in a Paizo stat block they should be rendered, regardless of if they're an attack or defensive or interaction. They don't have a meaning otherwise.

**Comment by bland-html** [comment]
I guess, is there a problem assigning a meaning to them or is that against
the team's design philosophy because it's not core PF2E? I mean, I get it,
but I'm curious why even have that option there at all if it has no meaning
other than in reference to a Paizo stat block?

**Comment by TMunsie** [comment]
We could have called them A, B, C but that’s not what Paizo did. The problem with giving it more meaning is that Paizo doesn’t use them consistently. We don’t choose which one makes most sense as a label. We choose the label so that when the sheet is rendered it looks like the stat block in the book. If we started giving them meaning and icons both of those things would no longer occur. In the end, adding these icons isn’t a core mechanic and since they are almost exclusively for NPCs, the use case is pretty weak. For PCs you get the action icons and if you want something additional a person can modify the titles to add something instead. Nothing is stopping anyone from homebrewing a letter or icon in their own world on their character sheet.

**Comment by bland-html** [comment]
That's fair. Thanks for the responses and explanations.
