### ISSUE TITLE
PF2 system keeps warning me about expired modules

### ISSUE THREAD

**Issue by DarKDinDoN** [foundryvtt/pf2e#2859]
Hello,

I have old modules or modules not up-to-date.
These modules are not officially compatible with the latest version of Foundry, but are working great nonetheless.

I think a lot of modules are not officially up-to-date with the latest version of Foundry but are still working.
Some modules are even up-to-date and compatible with V9, but do not declare it in the manifest (some of Kandashi's modules in mind).

Is it possible to find a better way to warn us about these modules without spamming us every single time we load the page?

https://github.com/foundryvtt/pf2e/blob/424373c9cf4043d44fd6924cf47f2b617c066c9a/src/scripts/hooks/ready.ts#L50
![vivaldi_sseW8TOM68](https://user-images.githubusercontent.com/1687854/177411125-50690a9d-199a-4008-b7a9-748b6a8b25ce.png)

Thx!

**Comment by TMunsie** [comment]
We tried the “warn once” approach and still received a lot of troubleshooting requests that, after a significant amount of time and effort, turned out to be due to a deprecated module.

We discussed this as a group and decided to do this “warn everytime” for a practical reason. It is up to the modules and their developers to state they are compatible and regardless of how well something works if it does not state compatibility then the end user should be warned. This is a measure to stop troubleshooting coming to the system level, which is universally what end users tend to do.

Our recommended solution is to contact the module developers and tell them to update their modules to indicate compatibility. For them it is a one line change in their manifest file.
