### ISSUE TITLE
Feature Request: @Action and/or the ability to change skills in a rollable button for actions 

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#2906]
At the moment it seems that the `skill` parameter in the inline action has been omitted, just wondering if that could be added in so you could make a rollable button with different skills like this for instance:
`ChatMessage.create({ content: '<span data-pf2-action="climb" data-pf2-skill="acrobatics" data-pf2-glyph="A" data-pf2-dc=20>Acrobatics (Climb)</span>'});`
And if possible we might be able to see an `@Action` In-line Action Buttons.

**Comment by JDCalvert** [comment]
The `@Action` could instead be an additional option inside a `@Check`, so something like `@Check[type:athletics|dc:10|action:climb]`. This gives more than `@Check[type:athletics|dc:10|traits:action:climb]` because the climb action macro adds the action name and roll notes:
![image](https://user-images.githubusercontent.com/38069151/178102290-91e71d0e-bee9-4462-9c13-75f0dea10819.png)
