### ISSUE TITLE
Elite NPC Adjustment Adding +6 To Spell Damage

### ISSUE THREAD

**Issue by Vaizt** [foundryvtt/pf2e#3470]
Not sure if this has been address already, but in the current stable release enabling the Elite adjustment will add the base +2 and the limited ability +4 to spell damage instead of replacing the +2 with the +4. I've tested on multiple NPCs with all modules disabled.

**Comment by ebuckle** [comment]
This has already been fixed on master.

Using the ``Necromancer`` NPC from the bestiary:
![image](https://user-images.githubusercontent.com/33088613/184492912-ba332069-e2ba-4afa-b2eb-5f79b7885a6b.png)
Non-Elite Electric Arc damage.
![image](https://user-images.githubusercontent.com/33088613/184492923-668b73b5-c6ea-49a2-b7c5-7108972d734e.png)
Elite Electric Arc receiving additional +2 since it's not a limited ability.
![image](https://user-images.githubusercontent.com/33088613/184492935-c0622b01-b826-4ecb-b2e7-506d4802f53c.png)
Elite Lightning Bolt receiving +4 since it's a limited ability.

**Comment by TikaelSol** [comment]
Closing as this is fixed in 4.0
