### ISSUE TITLE
Hand of the Apprentice should be available as a Universalist 1st Level Class Feat

### ISSUE THREAD

**Issue by yorkshirelandscape** [foundryvtt/pf2e#3541]
Hand of the Apprentice should be available as a Universalist 1st Level Class Feat. It's Uncommon, but only because it's only available to Universalist wizards. As it is, you have to add it as a Homebrew Item.

**Comment by Shandyan** [comment]
I've looked at the choiceset, and the issue is that the Universalist choiceset will only return wizard feats without a pre-requisite, rather than feats without a pre-req OR with a pre-req of universalist. I don't know how to tweak the choiceset to make it cover both options, but that's the source of the error.

```
{
  "adjustName": false,
  "choices": {
    "query": "{\"system.featType.value\":\"class\",\"system.level.value\":1,\"system.prerequisites.value\":[],\"system.traits.value\":{\"$elemMatch\":\"wizard\"}}"
  },
  "key": "ChoiceSet"
}
```

**Comment by KSops** [comment]
Resolved by https://github.com/foundryvtt/pf2e/pull/4734
