### ISSUE TITLE
Cannot Set Ability Score to Lower than 8

### ISSUE THREAD

**Issue by Hexygon** [foundryvtt/pf2e#3664]
**Foundry Version:** 9.269
**PF2E Version:** 3.13.5.16 (checked with release and master by @avagdumortesin )

**Problem:** Unable to set a character's ability score to less than a value of 8. Attempting to do so automatically reverts any number less than 8 to 8.

**Steps to Reproduce:**
From within a PC's sheet, open the Ability Score Edit Dialogue
Select "Use Custom" from the Ability Score Method
Within any ability score set the value to a number less than 8

**Comment by sturteva** [comment]
In the core game, a Player Character can't start with a score lower than an 8 even when using the Voluntary Flaws optional rules. This is because you can only apply a single flaw to an ability score, unless a boost has also been applied to that ability score (canceling each other out essentially). I've included the relevant rule below, bolding done for emphasis. 

> Optional: Voluntary Flaws
Sometimes, it’s fun to play a character with a major flaw even if you’re not playing an ancestry that imposes one. You can elect to take two additional ability flaws when applying the ability boosts and ability flaws from your ancestry. If you do, you can also apply one additional free ability boost. These ability flaws can be assigned to any ability score you like, but **you can’t apply more than one ability flaw to the same ability score during this step unless you apply both of the additional ability flaws to a score that is already receiving an ability boost during this step.** In this case, the first ability flaw cancels the ability boost, and the second ability flaw decreases the score by 2. Likewise, as an exception to the normal rules for ability boosts, you can apply two free ability boosts to an ability score receiving an ability flaw during this step; the first ability boost cancels the ability flaw, and the second ability boost increases the score by 2. For example, a dwarf normally gets an ability boost to Constitution and Wisdom, along with an ability flaw to Charisma. You could apply one ability flaw each to Intelligence and Strength, or you could apply both ability flaws to Wisdom. You could not apply either additional ability flaw to Charisma, though, because it is already receiving dwarves’ ability flaw during this step.

https://2e.aonprd.com/Rules.aspx?ID=66

With all of that being said, I leave it to the System folks to determine if the system should still allow homebrew/custom to go below an 8 in an ability score.

**Comment by TMunsie** [comment]
> In the core game, a Player Character can't start with a score lower than an 8 even when using the Voluntary Flaws optional rules. This is because you can only apply a single flaw to an ability score, unless a boost has also been applied to that ability score (canceling each other out essentially). I've included the relevant rule below, bolding done for emphasis.
> 
> > Optional: Voluntary Flaws
> > Sometimes, it’s fun to play a character with a major flaw even if you’re not playing an ancestry that imposes one. You can elect to take two additional ability flaws when applying the ability boosts and ability flaws from your ancestry. If you do, you can also apply one additional free ability boost. These ability flaws can be assigned to any ability score you like, but _**you can’t apply more than one ability flaw to the same ability score during this step unless you apply both of the additional ability flaws to a score that is already receiving an ability boost during this step.**_ In this case, the first ability flaw cancels the ability boost, and the second ability flaw decreases the score by 2. Likewise, as an exception to the normal rules for ability boosts, you can apply two free ability boosts to an ability score receiving an ability flaw during this step; the first ability boost cancels the ability flaw, and the second ability boost increases the score by 2. For example, a dwarf normally gets an ability boost to Constitution and Wisdom, along with an ability flaw to Charisma. You could apply one ability flaw each to Intelligence and Strength, or you could apply both ability flaws to Wisdom. You could not apply either additional ability flaw to Charisma, though, because it is already receiving dwarves’ ability flaw during this step.
> 
> https://2e.aonprd.com/Rules.aspx?ID=66
> 
> With all of that being said, I leave it to the System folks to determine if the system should still allow homebrew/custom to go below an 8 in an ability score.

Per the CRB the dice rolling alternative method of assigning ability scores (CRB 20) does allow for scores below 8 and Table 1-1: Ability Modifiers does go down to an ability score of 1. So a character can start with scores below 8, which is why this has the bug tag and not the wontfix tag :)

**Comment by sturteva** [comment]
Consider me bashfully wrong and now looking into the bug

**Comment by TMunsie** [comment]
LOL; You just missed the discussion that was held privately :)

We talked about it and it shouldn't be hard to remove the cap, but we only want to do that on the custom scores part.
