### ISSUE TITLE
Low-light vision doesn't treat low-light as bright light.

### ISSUE THREAD

**Issue by Phreddalicious** [foundryvtt/pf2e#3962]
I tested using three characters:  One with darkvision, one with low-light vision, and one with normal vision.  When in bright light, they all see the light as bright.  When in darkness, the darkvision can see, but the other two cannot.  (This is expect so far.)  When in dim light, the character with Darkvision sees as though it's bright light, but the other two characters (including the low-light vision character) still see it as dim light.

**Comment by stwlam** [comment]
Concealment checks aren't implemented, so low-light vision has nothing to it at the moment.

**Comment by Phreddalicious** [comment]
I'm not talking about concealment or anything, just the lighting in the scene.  It changes for the Darkvision character when it's dim light, but not for Low-light characters.

**Comment by TMunsie** [comment]
If you read the specific text “ A creature with low-light vision can see in dim light as though it were bright light, so it ignores the concealed condition due to dim light.”  What it does not say is that “A creature sees dim light the same as bright light”. The only difference is mechanical: a creature with low light vision does not need to make concealment checks in an area of dim light, and there are several feats where being able to determine dim light regions becomes important.

This has been discussed and debated and the system implementation is as we believe the rules are written.

**Comment by Phreddalicious** [comment]
Then why does Darkvision work differently?  If what you say is the case, then the problem is that dim light becomes bright light for characters with Darkvision.

**Comment by TMunsie** [comment]
Because until V10 shaders existed we couldn’t really do three different things. Darkvision may be revised in the future, but likely not immediately as there are now a lot of more important sense-related things to work on. 

We are doing the most correct things we can. If you don’t like it you’re always welcome to code a module to override the behaviour.

**Comment by Phreddalicious** [comment]
It's all good.  Just trying to figure out what's actually wrong, and if it's worth fixing.  It's not.

**Comment by TMunsie** [comment]
We also debated the darkvision thing. It seems silly that darkvision would stop someone seeing all colour in dim light. But what it should probably do is increase black and white contrast instead of colour contrast (kind of what we do for fetchling vision). That *might* now be possible (and would be super cool). Greater darkvision is going to be a massive pain…

**Comment by stwlam** [comment]
> Ah. "A creature with darkvision or greater darkvision can see perfectly well in areas of darkness and dim light, though such vision is in black and white only." So, the problem is actually that those with Darkvision see things in color in dim light.

For PCs, it's different:
> You can see in darkness and dim light just as well as you can see in bright light, though your vision in darkness is in black and white.
