### ISSUE TITLE
Inline Skill Checks break if CSS is changed / if journals are altered in appearance

### ISSUE THREAD

**Issue by Garsondee** [foundryvtt/pf2e#4273]
If I type

@Check[type:athletics|dc:20]{Athletics}

into a journal or chat with no modules installed it automatically formats that as a clickable skill check. However, if I have installed any modules which change the journal's appearance such as Storyteller (https://github.com/Xbozon/storyteller) or Custom Journal (https://github.com/Fair-Strides/FVTT-Custom-Journal-Theming/tree/v9-journals) then using the exact same @check text doesn't work. I am posting this here because having discovered that this breaks in multiple modules I'm assuming (perhaps incorrectly) that this is an issue with the game system or with Foundry itself.

What is interesting is that:

[[/br 1d4 #Breath Weapon Recharge]]{1d4 rounds}

Actually continues to work properly which leads me to think it is the game system and not Foundry itself which is breaking.

I have confirmed that this error exists in v9 and v10 of Foundry.

**Comment by stwlam** [comment]
This doesn't happen with pathfinder 2e premium modules. At a glance it appears to be a simple incompatibility with those two modules you list.

**Comment by Garsondee** [comment]
> This doesn't happen with pathfinder 2e premium modules. At a glance it appears to be a simple incompatibility with those two modules you list.

Should I be posting this bug in their githubs instead? (I have already posted this to one of them) - apologies if I've ended up putting this in the wrong place, very new to github.

**Comment by stwlam** [comment]
I'll leave this issue open in case someone else has a different opinion, but without other context it does appear to be a module issue rather than a system one.

**Comment by TikaelSol** [comment]
Man I feel sorry for the github user named Check. Anyways this is kind of expected for heavy handed UI stuff. BB / AV don't use a custom journal sheet, relying instead on heavy CSS work. Outlaws and Blood Lords though do use custom journal sheets and those both work fine. Looking quickly at Storyteller it looks like they are registering a new sheet, and we know that approach is workable since Sigil has done it for the two premium modules. I'm going to say this is definitely a module issue and go ahead and close it.
