### ISSUE TITLE
AdjustModifier RE cannot always adjust modifiers on spell attack rolls and never on DCs

### ISSUE THREAD

**Issue by Cerapter** [foundryvtt/pf2e#4414]
Easiest way to test it is to apply Frightened to a spellcaster, then try the following REs:

```json
{
    "key": "AdjustModifier",
    "suppress": true,
    "selector": "spell-dc",
    "slug": "frightened"
}
```

```json
{
    "key": "AdjustModifier",
    "suppress": true,
    "selector": "spell-attack",
    "slug": "frightened"
}
```

The penalties from frightened will not be suppressed.

If you change the selector to `"all"`, the spell DC will still have Frightened applied to it, but spell attack rolls will have them suppressed.

If you change the selector to `"spell-attack-dc"`, the spell attack rolls will have the Frightened penalties suppressed, but not if you change it to `"spell-attack-roll"` or `"attack-roll"`.

**Comment by CarlosFdez** [comment]
I did a partial fix, which handles the spell-attack-dc and all selector variants, but child domains targeting a main domain (such as a spell-attack adjustment targeting an all modifier such as frightened) remain broken. Since this has never worked, and its a major change to get it fixed which might break something, I'd like to go for it after the next hotfix to give it some time to bake.
