### ISSUE TITLE
There should be a visual indication of flanking arrangements

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4534]
I would like an indication for players to see when flanking is in effect. I think it would help alot of gms and players to see that when players are flanking a creature or vice versa that a satus icon appears telling them that the creature is flanked. and also when they decide to attack that it shows the flanking bonus in the roll dialogue. 

it would be a nice ui improvement.

**Comment by cepvep** [comment]
As discussed on the #pf2e-system channel, while it shouldn't put flat-footed on the token, or even claim the target is flat-footed in order to avoid leaking info for all around vision etc,I think some visual indicator for the person targeting would be nice, just to verify that the position is valid for flanking.. 

In my mind, a small box that appears on the targeting indicator when flanking, that has hover text stating some variant of "You are in position to flank this creature". High quality Pic attached as an example


![ss (2022-10-23 at 02 35 05)](https://user-images.githubusercontent.com/116499012/197395875-d141d344-7453-4399-bc60-55cef7d6d4af.png)

**Comment by ThingsCouldGetDicey** [comment]
yes i like the idea for it only being visible for the gm and the players who get into a flanking position.

other pcs who are not in flanking range should not see if its possible to flank or not to prevent metagaming.

more accuratley to my claim id like to have a visual indication more than anything.

**Comment by JulieWinchester** [comment]
Maybe this issue should be closed as completed?
