### ISSUE TITLE
[Feature Request] Additional kind of crits

### ISSUE THREAD

**Issue by Erfar** [foundryvtt/pf2e#4791]
Currently game settings allow to double damage or dices. Please add 3rd option to take maximum of "basic damage" and roll only additional dices.

**Comment by Drental** [comment]
Double the dice and double the damage are variant rules in the CRB, what you suggest here is not. We do not actively build homebrew rules into the system usually.

Also, this is far more complex to do than one might think because of fatal on the "how does it even work" side and because of the code that does the rolls on the implementation side.
