### ISSUE TITLE
Necromancer block - Correction?

### ISSUE THREAD

**Issue by shadydeath** [foundryvtt/pf2e#4972]
Suggestion to correct the stat block in the system for Necromancer AoN Link: https://2e.aonprd.com/NPCs.aspx?ID=929
To Int instead of Cha.
Looks like that should be the right one considering using wizard  preparation.

**Comment by TikaelSol** [comment]
It definitely was int before but looks like all NPCs got their spellcasting ability set to charisma by our extract script. I think we can use this as a hint to just kill that info since it's not at all based in the rules for NPCs, they just have a DC not one calculated from ability scores. It does impact some spells that deal + modifier damage but that's a problem inherent in how Paizo designed the NPCs and spells, giving us nothing to base that automation off of other than our best guess which we can make programmatically.

**Comment by stwlam** [comment]
No rules governing this, so nothing we can really do.
