### ISSUE TITLE
Dreshkan's Needle Spray DC

### ISSUE THREAD

**Issue by elemorelli** [foundryvtt/pf2e#4985]
On the Dreskhan Needle Spray Attack, there's a paragraph that says:

`Note: Paizo did not provide a listed DC for this ability. The suggested DC to use per the GMG is DC 19 Basic Reflex`

https://github.com/foundryvtt/pf2e/blob/master/packs/data/abomination-vaults-bestiary.db/dreshkan.json#L348

But now in the hardcover release it has been fixed and now it says:

`The dreshkan braces itself on all four limbs and sprays needles at as many creatures as it would like in a 30-foot cone, dealing 2d4 piercing plus 2d8 electricity damage (DC 21 basic Reflex save).`

Also, there's an official response from one of the Paizo Developers here confirming that should be DC 21:

https://paizo.com/threads/rzs43blf?2-Hands-of-the-Devil#19

**Comment by TMunsie** [comment]
Things posted by developers on forums, unless they are specific ones for errata, aren't normally included (there is a reason, and it was explained to us by an author about how errata is done for the system - the author or developers word isn't considered enough formally). That being said, the hardcover is errata-equivalent, so that is an awesome reference :)
