### ISSUE TITLE
Magic Missile and Dangerous Sorcery Interaction

### ISSUE THREAD

**Issue by Bam4k** [foundryvtt/pf2e#5426]
When casting Magic Missile because it does not allow you to select the level you cast it at or the number of actions used the incorrect amount of damage is generated when combining with certain class feats, the most common being the Sorceror's Dangerous Sorcery. It adds the damage bonus to every individual missile which is too much damage. Options on how to cast the spell could make for better calculations.

**Comment by TikaelSol** [comment]
The system does not and probably won't handle magic missile. It needs special handling since the spell can deal the dangerous sorcery damage on each missile if you split up the missiles. The PF2e Workbench module includes a Magic Missile macro that tackles all of this. You can also grab the macro from Symon's gitlab https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Magic%20Missile.js if you don't want to use the module.
