### ISSUE TITLE
Prevent "Dropped" items from counting towards total bulk

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#5528]
They should count as 0 bulk, regardless of their carried/worn bulk.

Screenshot of bug:

![image](https://user-images.githubusercontent.com/6516621/211068955-968c5207-6518-4315-a72f-937e1381e106.png)

Feel free to close this if you think the system should not support this feature, and [PF2E Workbench should instead](https://github.com/xdy/xdy-pf2e-workbench/issues/605).

**Comment by TMunsie** [comment]
We discussed this a long time ago. The purpose of dropped is meant to be a very temporary tracking thing. If we were to implement this, we would like implement something that would remove the object from inventory and drop it on the canvas.

What is the point or utility of making dropped be more than a reminder. You're not going to drop something permanently and leave it in your inventory. Presumably you'll pick it up and proceed on your adventuring day. If we automated encumbrance there might be a valid use case, but until we do that it just doesn't really seem to matter. If someone pushes code we would probably accept it, but there are more important issues to close than something that is ultimately cosmetic.

**Comment by shemetz** [comment]
Thanks, I wasn't aware this was very temporary.  And yes, I was thinking of encumbrance automation, and wasn't sure if the change needed to happen here or in the module that already does it.

**Comment by shemetz** [comment]
@stwlam now that [you added encumbrance automation in 5.2.0](https://github.com/foundryvtt/pf2e/pull/8836), can we reopen this request?

**Comment by mkahvi** [comment]
This problem seems to persist. Shouldn't the option be removed until it actually does something?

Temporary dropping IMO makes sense since you might just be in scene where it makes sense to temporarily drop something to deal with bulk issues. Not to mention it supports sceneless theatre-of-the-mind play.

**Comment by TMunsie** [comment]
Because of things like the party stash this is an exceptionally low priority. If someone wants to code it it likely could be considered, but there are other solutions. Dropped as a temporary reminder is still the primary use case, although with the swap action it is even less useful. 

As for removing it, it still fulfills the initial purpose. Stashing the item elsewhere to deal with encumbrance is a more likely workflow. “I put it in my house/hotel room/bag of holding” is a more likely thing than walking into a fight and spending the first round throwing a ton of the stuff on the ground. If my players started doing that they would soon find a teleporting monster running in and grabbing their things :)

Leaving this as wontfix for now.

**Comment by mkahvi** [comment]
> spending the first round throwing a ton of the stuff on the ground.

More likely a large heavy bag is dropped and that's it. And if they want to spend the actions for it, why not?

**Comment by TMunsie** [comment]
> not?

No where does it say it won’t be allowed. What this thread says is that there are already ways to do it and it is just a very, very low priority to automate something like this further as the use case it was created for was different. Code it and submit it as an option and if it passes review and meets the system ultimate design goals it might be added. There is only so much volunteer development time and the ask here has an inconvenient answer that works, not one that is actually hard for a player to do. So you can do it and the system doesn’t stop you. It just is more complicated than changing the status to dropped.
