### ISSUE TITLE
Mark for Death feat's Toggle is not upgrading deadly dice for qualifying weapons

### ISSUE THREAD

**Issue by ericdnielsen** [foundryvtt/pf2e#5775]
My player is using a war razor (deadly d6) so when the Mark for Death Toggle is set, it should upgrade to deadly d8, and its not.  It still rolls the d6.  I'm also not seeing the backstabber trait show up anywhere, but that may or may not be a separate issue.

**Comment by TikaelSol** [comment]
Backstabber is adding fine for me but I can confirm that the deadly dice addition is being ignored. I think this is because we are not removing the deadly d6 and the system just grabs the first of those traits.

We could add additional REs to remove the old deadly trait, but a cleaner solution would be to have a replace mode for AdjustStrike that would perform an add and subtract in one go.

**Comment by JDCalvert** [comment]
This is due to an issue caused by #5271 (line [link to line](https://github.com/foundryvtt/pf2e/pull/5271/files#diff-abb5dd2ae9f66d816733e65f72a23adcb4b0f6f9c384c6a1dc8fd567d3c16941R163)).

In the example of a rapier, the weapon has the `deadly-d8` trait. The rule element is trying to add `deadly-d10` and finds that there's already `deadly-d8`. Because `deadly-d10` is "bigger" than `deadly-d8`, `deadly-d8` is removed, but that rogue `return` statement stops the process before `deadly-d10` can be added.

The later rule element then adds `deadly-d6` because there's no other `deadly` trait on the weapon. #5866 fixes this..
