### ISSUE TITLE
Critical Damage Type is blank on weapon sheets' custom damage

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#5987]
![image](https://user-images.githubusercontent.com/32039708/215270557-a0529f95-b895-4b73-a86c-398bb5106ed3.png)

PF2e v4.6.8
Foundry v10.291

**Comment by TikaelSol** [comment]
I think if we made a UI for damage dice REs this whole section could go. The reason I wanted it kept in before was for ease of use with the Battlezoo monster parts system, but since we have a UI for flat modifiers and notes I don't see much reason to keep it if we can make the rest easy to do properly.
