### ISSUE TITLE
Quill Spray leveled bleed damage not calculated

### ISSUE THREAD

**Issue by MSAbaddon** [foundryvtt/pf2e#6207]
![image](https://user-images.githubusercontent.com/66370966/217106801-46ef8c57-12cc-4468-829c-05a8e66247a0.png)

Currently, the roll formula `[[/r (ceil(@actor.level/2))[bleed]]]` isn't calculated correctly:
![image](https://user-images.githubusercontent.com/66370966/217106976-013c5507-70c4-482a-953b-8b41ba5c6491.png)

However, the same roll formula with a dice added works just fine (`[[/r (ceil(@actor.level/2)d4)[bleed]]]`):
![image](https://user-images.githubusercontent.com/66370966/217107141-7236f993-7ae4-4e0c-8d90-c23d9e49eb2a.png)

**Comment by glont** [comment]
Fixing that could theoretically be done by adding a `d1` to the roll formula: `[[/r (ceil(@actor.level/2))d1[bleed]]]`, but when I read the description of the feat, it seems to be `ceil(@actor.level/2)` is maybe not correct. In the feat description it says: At 11th level and every even level thereafter, the piercing damage increases [...]

This seems to mean, that the damage goes up on 
- Level 11 to 6d8 and 6
- Level 12 to 7d8 and 7
- Level 14 to 8d8 and 8
- Level 16 to 9d8 and 9
- Level 18 to 10d8 and 10
- Level 20 to 11d8 and 11.
 
The formula using `ceil(@actor.level/2)` would be lower than required on even levels from level 12 onwards, because ceil(12/2) = 6 instead of 7, and so on. A formula using `floor(@actor.level/2) + 1` would be to high for level 10. floor(10/2) + 1, would be 6 instead of 5.
