### ISSUE TITLE
BaseSpeed permanently modifies NPC speed despite predicates

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#6365]
Video shows the issue in action, this happens in both compendium, actor sidebar, and token versions of the creature.

https://user-images.githubusercontent.com/32039708/218793906-abf2d29d-fd55-446f-895b-fecd0f1b7ee5.mp4

**Comment by simonward** [comment]
The issue is that templates/actors/npc/partials/sidebar.hbs has an editable field for the NPC's speed that shows speed.value rather than speed.total. Might need a non-editable field that shows total speed?

`<input type="number" class="land-speed-value" name="system.attributes.speed.value" value="{{data.attributes.speed.value}}" placeholder="0"/>`

**Comment by velara** [comment]
To add on to this, since it seems to be a related issued. If you use the following rule element {"key":"ActiveEffectLike","mode":"add","path":"system.attributes.speed.value","value":-5} the NPCs speed will decrease each and every time you open the character sheet. While be no means exhaustive I tested couple other paths and didn't have the same issue so it does seem to be speed specific.

I suspect the root issue is the same.

I know it didn't used to do this because I've been using this method for a while for my ancestry templates to get around the fact that flat modifiers to speed don't show up on the NPC sheet because it displays the value not the total.
