### ISSUE TITLE
NPC sheets do not display bulk values

### ISSUE THREAD

**Issue by magispitt** [foundryvtt/pf2e#6427]
![image](https://user-images.githubusercontent.com/96706608/219767593-bfb46d40-6dc5-4c07-beb4-3869f791929d.png)

NPCs do not currently track bulk, as seen above (Troubadour from the NPC Gallery).

When using the PF2e Workbench module, there is an option to apply encumbrance; I assume this implies that bulk can be tracked on NPCs sheets.

![image](https://user-images.githubusercontent.com/96706608/219768072-edd1ba62-4b5b-402d-83ed-72bb41df9d04.png)
![image](https://user-images.githubusercontent.com/96706608/219768131-5e8c47da-fe24-49a3-a274-c38891ffd8ef.png)

**Comment by avagdumortesin** [comment]
There's nothing on that Workbench option that indicates that it should apply to NPCs; it simply automatically applies the Encumbered condition if your bulk warrants it. 

If you can find documentation in the published books that indicates that we should be tracking bulk on NPCs, please provide the book name and page number, and we'll review that. Otherwise, this is not an issue.

**Comment by stwlam** [comment]
I don't think there's a problem with displaying it

**Comment by 7H3LaughingMan** [comment]
I would like to second this feature if possible. My part just purchased a bunch of Riding Horses to speed up movement during hexploration with the plan to also use them to carry gear they don't need on their person in combat. I looked into copying the bar from the player sheet to the npc sheet and it sort of works, just looks all wonky do to styling which I am not very good at. So, implementing this feature should just require editing the templates and style sheets.

![image](https://github.com/foundryvtt/pf2e/assets/117857081/85b06bb6-85ab-4aa1-a7bd-341c4b0e3d1c)
