### ISSUE TITLE
Opt-out rules-based vision for a scene.

### ISSUE THREAD

**Issue by HenriDeh** [foundryvtt/pf2e#6927]
Currently you either have rules-based vision for all your scenes, or for none. 
I think adding an option to opt-out in the scene configuration panel would be interesting for scenes that are maps that a party token explores, for example. That is, an option to disable global illumination, maybe with a message explaining it does not follows the pf2e vision rules.
This is going to become more and more relevant with the Kingmaker AP being played.

**Comment by TMunsie** [comment]
Why would you not just create a shared part actor for such a map? I'm not certain of the use case here and I'm not sure how kingmaker comes into play? Just because it is hexploration? Why have vision on at all in that scene if it is just a map?

Here is a sample hexploration map that I used yesterday. The UI could be a lot better (I made the hex opacity 30% on entry and then hidden when they were fully explored) but that really has nothing to do with vision. If you can explain a better use case that would be helpful. And why turning off scene vision isn't enough and you need some weird non-rule-based vision version (preferably with citation to a Paizo usage) is required to achieve that. We don't want to invest time for someone to turn around when we're done and say "I didn't mean that!"

![image](https://user-images.githubusercontent.com/25963508/224840407-23913ad8-e64b-4019-9321-8ed05ba96b0f.png)

**Comment by HenriDeh** [comment]
> Why would you not just create a shared part actor for such a map?

That's the idea yes. But that marker needs to have a vision limitation in distance to work on a map that is unknown to the party.

> Here is a sample hexploration map that I used yesterday. The UI could be a lot better (I made the hex opacity 30% on entry and then hidden when they were fully explored) but that really has nothing to do with vision.

How did you do that ? Perhaps I overlooked an existing feature that does what I need (I swear I spent more time trying than I should have).

> why turning off scene vision isn't enough 

When you turn off scene vision, the party token has unlimited sight distance, so it can see the whole map and there's no fog of war (unless you manually grid the map with walls...). 

> preferably with citation to a Paizo usage

It is not to work like Paizo rules, it just makes sense to only know the map where the party went, and to remember previously explored hexes. It's just like normal dungeon exploration, except that there you have walls to block your view. 

I don't know if I made it clear. Don't hesitate to insist if you need more explanations.

**Comment by InfamousSky** [comment]
Take a look at the World Explorer module

**Comment by TMunsie** [comment]
More options is more maintenance and that is a pretty substantial thing to ask volunteer developers to do. Without a concrete reason to move forward I don't really see the investment in effort here. People can either choose to use vision per the rules Paizo laid out for vision or not. Hexploration is weird, but disabling rules based vision doesn't seem to solve that problem in any meaningful way. I don't see a case even for hexploration where you would use what you're asking for. At least one that can't be done with rules based vision as is. (If you want to limit vision for a party make a part token with no special vision, set the scene darkness, and put a bright light radius on the token, for example. Nothing in RBV prevents something like that. Otherwise, for hexploration, you're looking at walls that block light, and then turning on a light in each cell as you move. RBV doesn't prevent that.

If you can come up with a specific use other than "I would like the option in case that I need it in the future" that requires something other than RBV then we can look at it. I don't see how disabling RBV solves the hexploration problem. At least not in a nice way that isn't solved several other (arghuably better) ways in core or by modules.
