### ISSUE TITLE
Poisoned Lock should link to the Drained condition

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/pf2e#7506]
For the Poisoned Lock, under Cladis Poison at stage 3 it is written as:

Stage 3 [[/r 3d6[poison]]] damage and drained 2 (1 hour)

When in reality it should be written as:

Stage 3 [[/r 3d6[poison]]] damage and @UUID[Compendium.pf2e.conditionitems.4D2KBtexWXa6oUMR]{Drained 2} (1 hour)

**Comment by simonward** [comment]
Since the Drained 2 condition is linked already, it's typically not linked again.
<img width="387" alt="Screen Shot 2023-04-22 at 10 52 40 AM" src="https://user-images.githubusercontent.com/1904698/233799398-55b5f9bc-d75e-4f94-ac98-433cf08ed85c.png">

https://github.com/foundryvtt/pf2e/wiki/Style-Guide#cross-linking
"If the same item is referenced again, it shouldn't be linked. The exception is for conditions with numerical values, where you should cross-link every unique numerical value."
