### ISSUE TITLE
Deathless acolyte of ugathoa Fast healing incorrect

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#7534]
https://2e.aonprd.com/Monsters.aspx?ID=1853

when draging on the fast healing to a pc it does different amounts of fast healing.  it should be 2 not 5. which is whats on the re. 

![image](https://user-images.githubusercontent.com/62528192/234043573-e1b21049-6a8b-4490-b5d6-da84cf6c9db7.png)

**Comment by cjneidhart** [comment]
This affects more than just the deathless acolyte, it also affects other NPCs that link to the Fast Healing action but list a value other than 5:

- Book of the Dead: Deathless Acolyte of Urgathoa (2), Deathless Hierophant of Urgathoa (4)
- Bestiary 1: Crimson Worm (20), Ofalth (2)
- Bestiary 3: Skinstitch (3)
- Extinction Curse: Obsidian Golem (15), Vitalia (10)
- PFS Season 1: Skeleton Corporal (1)
- PFS Season 4: Seldrick Dralston
- Strength of Thousands: Gluttonworm (10)

It doesn't affect NPCs with non-conditional fast healing like the voidworm, since they have rule elements on their own passive actions.

**Comment by simonward** [comment]
Those link to the Compendium ability which has a default of 5. That's intended to be used as a template for adding abilities to NPCs. For some of those, they should just have fast healing REs. For others, such as those that transmit an aura, we need an effect.

We could add an effect that uses the badge value.
