### ISSUE TITLE
Feats being recategorized into wrong type

### ISSUE THREAD

**Issue by Kana-Kuroko** [foundryvtt/pf2e#7678]
Having a strange bug with a custom class module I created. On my machine all of the feats are correctly categorized as Class Feats, but when I give the download manifest to others the feats are forcefully converted to Bonus Feats. A friend of mine checked the database code and they're still categorized as Class Feats in the db file but still being displayed as Bonus Feats once the module is installed in Foundry.

**Comment by stwlam** [comment]
We're going to need to see the module in order to come to any conclusions.

**Comment by Kana-Kuroko** [comment]
Here's the manifest for the module: ttps://raw.githubusercontent.com/Kana-Kuroko/ninjaClass-pf2e/master/module.json
And the full module itself: https://github.com/Kana-Kuroko/ninjaClass-pf2e

**Comment by stwlam** [comment]
OK, this is happening due to the data in the module's compendium data being quite old. They're migrated upon import, but not before the feat category is checked. We can ensure those are migrated earlier for that purpose. I would still recommend migrating your module's data, which can be done simply by importing each compendium and reexporting.

**Comment by Kana-Kuroko** [comment]
Thank you! I did an update near the end of the module's creation, so it's possible I grabbed an older version of my backups to add to the repo. I'll double check on that, and if not be sure to import/export if that doesn't solve it. Thank you again, I was at a loss for what to do to solve that on my own!
