### ISSUE TITLE
Request: add macro for locating dangling item references

### ISSUE THREAD

**Issue by robinsving** [foundryvtt/pf2e#8030]
Each update that comes will bring new and upgraded items. This is great, but it is hard keeping track, when you are a player, of which items that have changed.

Could we get a Macro, or similar, which would allow a user to parse all the items references of their assignes Actors and compare them to the system references to see if they look different. 
Sometimes a user may have added their own information to a piece of equipment so there would be some false positives, but I think that's fine.

**Comment by TikaelSol** [comment]
This is going to be out of scope for the system itself, but that kind of macro could be made rather easily. Rather than doing a deep diff of both items the most sensible thing to do would be to check if the `rules` arrays are the same. Since rule elements are primarily how items are automated. You could also check if the descriptions match. If you just went with the whole item you'd find that a lot of stuff is just not present in compendium data. The macro polo channel on the main Foundry discord can help out with that but the basic structure will be

get actor
get items on actor
filter items to only ones that have `flags.core.sourceId` present
loop over each item and compare it to the source item, adding the name to a list if it does not
output the list to chat or console.
