### ISSUE TITLE
ABP variant shouldn't eliminate speed item bonus

### ISSUE THREAD

**Issue by ViniciosCoelho** [foundryvtt/pf2e#8292]
### Description
Automatic bonus progression rules only states that bonuses to rolls and DCs should not be accounted. But when using this variant rule, the module ignores item bonuses globally.

#### How to reproduce
1. Have a world set with the ABP active.
2. Create a new Player Character.
3. Check the character speed.
4. Add the "Boots of Bouding" to it and equip them.
5. Check the speed again

##### Expected result
The speed should have a +5 item bonus increment.

##### Actual result
The speed is equal as before.

#### Observation
Take a look at `src/module/actor/character/automatic-bonus-progression.ts:135`. A possible solution would be to filter the `selector` attribute values by the ones that indicate rolls and DCs. But I'm not sure about this, it's just a suggestion.

**Comment by TMunsie** [comment]
We are unlikely to change this at present. There are a lot of issues and interpretations to ABP. We suggest asking Paizo to remaster the rules so that they are no longer overhauling a 600 page Rulebook in a page and a half. 

If you wish to change this we suggest that you change the rule element locally to potency.

**Comment by stwlam** [comment]
> Items that normally grant an item bonus to statistics or damage dice no longer do, other than the base item bonus to AC from armor.
