### ISSUE TITLE
Spells Calling Damage When Interacted With

### ISSUE THREAD

**Issue by dogstarrb** [foundryvtt/pf2e#8400]
I know you don't normally make changes based on modules, but I think this one is really on the pf2e end, and not necessarily intended. Ever since 4.12.x, when using DF Manual Rolls (I know, I know), every time a spell is interacted with (clicked on to expand the spell description, placed in a slot from the preparation menu, cast to chat) the base damage of the spell is called- and I think actually evaluated- even though it is not actually printed to chat. For example, when actually trying to print the damage of the spell from the chat card, the unheightened version of the spell will be called for, which is not printed, and _then_ the appropriately heightened spell damage is called for, and printed as intended. 
I am a beginner at best with code, but to the best of my understanding, the DF Manual Rolls _**does**_ check for if the roll is evaluated or not before prompting the user to input roll results. As this problem did not exist prior to 4.12.x, I believe something may have changed in the getdamage that is causing it to read as evaluated, which might not be the intention, I'm hoping.

**Comment by CarlosFdez** [comment]
I'll take a look when I'm no longer enraptured by the new shiny videogame that just released today

**Comment by CarlosFdez** [comment]
I found the cause, its a foundry thing, not a pf2e thing. evaluate({ async: false }) is called as part of the implementation of Roll#validate(). This has nothing to do with getDamage() in particular (other than it calling validate())

You'll need DF Manual Rolls to override validate to do whatever it is you need to, or ignore async: false. I don't know what it is you need, but that's why you're seeing the evaluate().
