### ISSUE TITLE
Support more operators than + and - in Spell Damage

### ISSUE THREAD

**Issue by DireDiamond** [foundryvtt/pf2e#9145]
This issue specifically happens with spell damage and nothing else that I've seen so far.

(its showing 9 instead of 7 due to another aura affecting me, there is nothing else affecting me past that)

![Capture](https://github.com/foundryvtt/pf2e/assets/14033324/13e6829f-c8f9-437e-b896-2276d3af362d)
![image](https://github.com/foundryvtt/pf2e/assets/14033324/50d58d30-8c0e-464a-aa83-c9fa3bc0f375)

**Comment by stwlam** [comment]
This is not how spell heightening is done, so you may be out of luck trying to get that to work.

**Comment by DireDiamond** [comment]
its not heightening that im trying to do, just to add half the character level to the damage, as if adding a mod.

**Comment by CarlosFdez** [comment]
It feels weird to do this, but I could try to leverage the reverse parser I built for @Damage for this, it would definitely solve it. Though it is definitely a bit weird.

**Comment by stwlam** [comment]
Yeah, I don't know if the use case justifies it. This is basically heightening done incorrectly.

**Comment by DireDiamond** [comment]
> Yeah, I don't know if the use case justifies it. This is basically heightening done incorrectly.

Its not tho. How will you add half your level to a spell with normal heightening rules, this is simple maths not working, as the level on its own works and you can do 1d6+level.

> It feels weird to do this, but I could try to leverage the reverse parser I built for `@Damage` for this, it would definitely solve it.

If it fixes math then why not ^^

**Comment by CarlosFdez** [comment]
The actual problem is that its not reporting that your formula is invalid. Spell is only for + and - joined simple modifier/die terms only. To accept modifiers and damage dice, it has to resolve into a simple list of dice and modifiers at the end of the day.

I agree with stwlam that its heightening done incorrectly, since it seems you're trying to do Kineticist homebrew, and spells are not intended for that. If you want my recommendation, add a flat modifier that with a selector for {item|id}-damage. That with some fancy formula math will get you what you're actually trying to do.

However, the new `@Damage` syntax supports converting more complicated formulas into simple terms, so its convenient timing. This is likely going to happen anyways since this refactor will allow us to kill some code, but its low priority.
