### ISSUE TITLE
Using Automatic Bonus Progression should allow armor's potency bonus to Armor Criticalization

### ISSUE THREAD

**Issue by robinsving** [foundryvtt/pf2e#9875]
How to recreate:

- Run ABP
- Create a lvl 15 character
- Observe Defence potency +2 to AC modifiers
- Equip Heavy Armor
- Slashing resistance should be "2 + the value of the armor’s potency rune for heavy armor" = 4, but is only 2

I will concede that the RAW says "potency **rune**", and there is no such rune in ABP. I'd still say the RAI is clear, and the Crit specialization should be the same as in a normal game

**Comment by TikaelSol** [comment]
Armor specialization isn't automated yet. Closing because the feature request to automate that is handled by another issue already but also because we implement ABP RAW, and suggest people tell Paizo to please fix their poorly written rules, or use the Automatic Rune Progression module to do what they think ABP should do anyways.
